### ISSUE TITLE
Missing PPPoE Luci App in WDR3500

### ISSUE THREAD

**Issue by modante** [libremesh/lime-packages#260]
I think is a package that is usefull to be included in the images. At least in the **lede-17.01.2-lime-default-ar71xx-generic-tl-wdr3500-v1-squashfs-factory.bin** is not included by default (although is easily installed).
Regards :-)

**Comment by peter-tank** [comment]
unsubscrib

On December 6, 2017 10:18:15 AM GMT+08:00, modante <notifications@github.com> wrote:
>I think is a package that is usefull to be included in the images. At
>least in the
>**lede-17.01.2-lime-default-ar71xx-generic-tl-wdr3500-v1-squashfs-factory.bin**
>is not included by default (although is easily installed).
>Regards :-)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/libremesh/lime-packages/issues/260

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aparcar** [comment]
@modante can you compare how big the package is? An image with and without the package installed? Maybe it has some additional dependencies bloating the image over 8MB

**Comment by dangowrt** [comment]
I also noticed the missing luci-proto-ppp (which is installed on
vanilla LEDE releases) on TP-LINK W8970B (Lantiq VRV200 xDSL router).
I guess it should become part of the lime-default flavour, because it
really isn't that big (3.7kB). Maybe just adding the 'luci'
meta-package instead of just luci-mod-admin-full and
luci-theme-bootstrap to the lime-default package-set would be the most
appropriate solution imho.

@p4u @G10h4ck @altergui
