### ISSUE TITLE
shared-state creates an unnecesary file when doing get

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#533]
Expected behaviour: for the get to be read-only
Actual behaviour: I called shared-state with a typo (one mispelled letter), and it created a file in /tmp/shared-state/data with that mispelled typo.
```
# shared-state get Dnsmasq-hosts.json
[]
# ls /tmp/shared-state/data/
... Dnsmasq-hosts.json ...
```

**Comment by ilario** [comment]
Maybe it gets created here, I did not check in order to confirm:

https://github.com/libremesh/lime-packages/blob/dcb099e2dbb861118eb737d704453f61b2e0d87c/packages/shared-state/files/usr/lib/lua/shared-state.lua#L48-L49

Due to the lack of documentation (#492) I have no idea if this is a bug or not.
@G10h4ck or @spiccinini could know.
For now, as it is not clearly a bug and its impact seems minimal, I am going to close this. Feel free to re-open.
