### ISSUE TITLE
if the kernel needs to kill a process, trigger a reboot

### ISSUE THREAD

**Issue by suarezwilliamf** [libremesh/lime-packages#610]
it may happen that because the device is running out of memory the kernel, using omkiller, may want to kill some processes.
the libremesh experience depends on many processes, so we should monitor their uptime or reboot them directly.
(this is @nicopace by the way :) )

**Comment by nicopace** [comment]
The reason why it is a reboot and not a service reboot, is that we don't know which service is the one that is eating the ram... and at that stage, we are late already for fixing it.
Also, we should think what happens if we reboot too many times... maybe the router could enter to a failsafe mode automatically... like at uboot... @spiccinini, what do you think ?

**Comment by ilario** [comment]
We could implement something like: 
if (uptime > 24h and free RAM < 2 MB) then reboot

But if it is a process filling the RAM, and not the tmpfs (/tmp), the OOM killer should work, I saw it acting just once and it killed LuCI which was the correct process to kill...

**Comment by ilario** [comment]
No solid solution and no interest in the last 4 years, closing
